"use client"

import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import './globals.css'
import { Montserrat } from 'next/font/google'

import Themcontext from '@/context/themcontext'


const bodyFont = Montserrat({ 
  subsets: ['latin'], 
  weight: ['400', '700', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <Themcontext>
          <div className= 'container'>
          <Navbar/>
          {children}
          <Footer/>
          </div>
        </Themcontext>
      </body>
    </html>
  )
}
